import type { Ingredient } from "./types";

export const INGREDIENTS: Ingredient[] = [
  {
    id: "chuoi-chin",
    nameVi: "Chuối chín",
    nameEn: "Banana, ripe",
    category: "qua",
    potassiumMgPer100gRaw: 358,
    typicalServingG: 120,
    notesVi: "Một quả vừa (~120 g) khoảng 430 mg Kali.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "khoai-tay",
    nameVi: "Khoai tây",
    nameEn: "Potato",
    category: "cu",
    potassiumMgPer100gRaw: 421,
    typicalServingG: 150,
    notesVi: "Luộc chắt nước hoặc ngâm + luộc hai lần giảm Kali rõ hơn nướng/chiên.",
    sourceIds: ["usda-fdc", "usda-nrf"],
  },
  {
    id: "khoai-lang",
    nameVi: "Khoai lang",
    nameEn: "Sweet potato",
    category: "cu",
    potassiumMgPer100gRaw: 337,
    typicalServingG: 130,
    notesVi: "Phổ biến ở Việt Nam; hấp/luộc giữ Kali cao hơn nếu không chắt nước.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "rau-muong",
    nameVi: "Rau muống",
    nameEn: "Water spinach",
    category: "rau",
    potassiumMgPer100gRaw: 312,
    typicalServingG: 100,
    notesVi: "Giá trị tham chiếu từ bảng thành phần thực phẩm khu vực / USDA rau xanh tương đương.",
    sourceIds: ["vndn-fct", "usda-fdc"],
  },
  {
    id: "cai-bo-xoi",
    nameVi: "Cải bó xôi (rau bina)",
    nameEn: "Spinach",
    category: "rau",
    potassiumMgPer100gRaw: 558,
    typicalServingG: 80,
    notesVi: "Rau rất giàu Kali. Luộc chắt nước giảm Kali nhiều hơn xào.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "bong-cai-xanh",
    nameVi: "Bông cải xanh",
    nameEn: "Broccoli",
    category: "rau",
    potassiumMgPer100gRaw: 316,
    typicalServingG: 90,
    notesVi: "Hấp giữ Kali cao hơn luộc.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "ca-chua",
    nameVi: "Cà chua",
    nameEn: "Tomato",
    category: "qua",
    potassiumMgPer100gRaw: 237,
    typicalServingG: 120,
    notesVi: "Nước sốt cà chua cô đặc làm tăng Kali/khẩu phần.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "bo",
    nameVi: "Bơ (quả)",
    nameEn: "Avocado",
    category: "qua",
    potassiumMgPer100gRaw: 485,
    typicalServingG: 70,
    notesVi: "Nửa quả đã là nguồn Kali lớn.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "xoai",
    nameVi: "Xoài chín",
    nameEn: "Mango",
    category: "qua",
    potassiumMgPer100gRaw: 168,
    typicalServingG: 150,
    notesVi: "Khẩu phần lớn vẫn đóng góp Kali đáng kể.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "du-du",
    nameVi: "Đu đủ chín",
    nameEn: "Papaya",
    category: "qua",
    potassiumMgPer100gRaw: 182,
    typicalServingG: 140,
    sourceIds: ["usda-fdc", "vndn-fct"],
    notesVi: "Thường ăn tươi.",
  },
  {
    id: "cam",
    nameVi: "Cam",
    nameEn: "Orange",
    category: "qua",
    potassiumMgPer100gRaw: 181,
    typicalServingG: 130,
    notesVi: "Nước cam ép giữ gần như toàn bộ Kali của quả.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "dua-hau",
    nameVi: "Dưa hấu",
    nameEn: "Watermelon",
    category: "qua",
    potassiumMgPer100gRaw: 112,
    typicalServingG: 200,
    notesVi: "Hàm lượng/100 g vừa phải nhưng khẩu phần thường lớn.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "nuoc-dua",
    nameVi: "Nước dừa tươi",
    nameEn: "Coconut water",
    category: "do-uong",
    potassiumMgPer100gRaw: 250,
    typicalServingG: 250,
    notesVi: "Một ly 250 ml có thể ~625 mg Kali — cần thận trọng khi tăng Kali máu.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "dau-den",
    nameVi: "Đậu đen (khô)",
    nameEn: "Black beans, dry",
    category: "dau",
    potassiumMgPer100gRaw: 1483,
    typicalServingG: 40,
    notesVi: "Giá trị cho hạt khô. Luộc chín tăng khối lượng, Kali/100 g chín thấp hơn khô.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "dau-phu",
    nameVi: "Đậu phụ",
    nameEn: "Tofu",
    category: "dau",
    potassiumMgPer100gRaw: 121,
    typicalServingG: 120,
    notesVi: "Đậu phụ mềm; đậu hũ chiên sẽ cô đặc hơn.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "gao-trang",
    nameVi: "Gạo trắng (gạo sống)",
    nameEn: "White rice, raw",
    category: "ngu-coc",
    potassiumMgPer100gRaw: 115,
    typicalServingG: 60,
    notesVi: "Cơm chín hấp thụ nước; Kali/khẩu phần thấp hơn nhiều loại củ.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "thit-heo-nac",
    nameVi: "Thịt heo nạc",
    nameEn: "Pork, lean",
    category: "thit",
    potassiumMgPer100gRaw: 362,
    typicalServingG: 100,
    notesVi: "Kho tàu: Kali ở thịt và một phần trong nước kho.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "thit-bo",
    nameVi: "Thịt bò",
    nameEn: "Beef",
    category: "thit",
    potassiumMgPer100gRaw: 318,
    typicalServingG: 100,
    notesVi: "Phở bò: nước dùng cũng chứa Kali từ xương/thịt/gia vị.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "ca-hoi",
    nameVi: "Cá hồi",
    nameEn: "Salmon",
    category: "ca",
    potassiumMgPer100gRaw: 363,
    typicalServingG: 120,
    notesVi: "Nướng giữ Kali cao.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "ca-basa",
    nameVi: "Cá tra / basa",
    nameEn: "Pangasius",
    category: "ca",
    potassiumMgPer100gRaw: 280,
    typicalServingG: 150,
    notesVi: "Giá trị gần đúng theo cá da trơn; dùng cho canh chua.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "sua-chua",
    nameVi: "Sữa chua",
    nameEn: "Yogurt, plain",
    category: "sua",
    potassiumMgPer100gRaw: 155,
    typicalServingG: 150,
    notesVi: "Sữa và chế phẩm sữa là nguồn Kali vừa.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "hat-dieu",
    nameVi: "Hạt điều",
    nameEn: "Cashew",
    category: "hat",
    potassiumMgPer100gRaw: 660,
    typicalServingG: 30,
    notesVi: "Khẩu phần nhỏ nhưng đậm Kali.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "lac",
    nameVi: "Lạc (đậu phộng)",
    nameEn: "Peanut",
    category: "hat",
    potassiumMgPer100gRaw: 705,
    typicalServingG: 30,
    sourceIds: ["usda-fdc", "vndn-fct"],
    notesVi: "Rang giữ Kali cao.",
  },
  {
    id: "nam-rom",
    nameVi: "Nấm rơm",
    nameEn: "Straw mushroom",
    category: "rau",
    potassiumMgPer100gRaw: 356,
    typicalServingG: 80,
    notesVi: "Nấm nói chung giàu Kali.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "bi-do",
    nameVi: "Bí đỏ",
    nameEn: "Pumpkin",
    category: "cu",
    potassiumMgPer100gRaw: 340,
    typicalServingG: 150,
    notesVi: "Canh bí phổ biến; ăn cả nước thì Kali gần đủ của nguyên liệu.",
    sourceIds: ["usda-fdc", "vndn-fct"],
  },
  {
    id: "gia-do",
    nameVi: "Giá đỗ",
    nameEn: "Mung bean sprouts",
    category: "rau",
    potassiumMgPer100gRaw: 149,
    typicalServingG: 50,
    notesVi: "Hay cho vào canh chua lúc gần tắt bếp.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "thom",
    nameVi: "Thơm (dứa)",
    nameEn: "Pineapple",
    category: "qua",
    potassiumMgPer100gRaw: 109,
    typicalServingG: 60,
    notesVi: "Dùng trong canh chua.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "hanh-tay",
    nameVi: "Hành tây",
    nameEn: "Onion",
    category: "cu",
    potassiumMgPer100gRaw: 146,
    typicalServingG: 40,
    sourceIds: ["usda-fdc"],
    notesVi: "Gia vị nền.",
  },
  {
    id: "toi",
    nameVi: "Tỏi",
    nameEn: "Garlic",
    category: "gia-vi",
    potassiumMgPer100gRaw: 401,
    typicalServingG: 8,
    notesVi: "Khối lượng nhỏ nên Kali tuyệt đối thấp.",
    sourceIds: ["usda-fdc"],
  },
  {
    id: "nuoc-tuong",
    nameVi: "Nước tương",
    nameEn: "Soy sauce",
    category: "gia-vi",
    potassiumMgPer100gRaw: 435,
    typicalServingG: 10,
    notesVi: "Muối và Kali đều cao theo muỗng canh.",
    sourceIds: ["usda-fdc"],
  },
];

export function getIngredient(id: string): Ingredient | undefined {
  return INGREDIENTS.find((item) => item.id === id);
}

export function requireIngredient(id: string): Ingredient {
  const ingredient = getIngredient(id);
  if (!ingredient) {
    throw new Error(`Unknown ingredient: ${id}`);
  }
  return ingredient;
}
