import type { Medicine } from "./types";

export const MEDICINES: Medicine[] = [
  {
    id: "spironolactone-25",
    inn: "Spironolactone",
    innVi: "Spironolacton",
    strength: "25 mg",
    formVi: "Viên nén",
    tradeNamesVn: [
      "Aldactone 25 mg",
      "Spironolactone 25 mg (DHG, Imexpharm, và generic khác)",
    ],
    potassiumEffect: "increase",
    mechanismVi:
      "Đối kháng aldosterone (MRA) — giảm thải Kali ở ống lượn xa.",
    adviceVi:
      "Theo dõi Kali và creatinine sau khi tăng liều. Nguy cơ tăng khi kết hợp ACEI/ARB/ARNI, NSAID, hoặc CKD. AHA/HFSA: nền tảng suy tim HFrEF.",
    relatedConditionIds: ["suy-tim", "tang-kali-mau", "benh-than-man"],
    sourceIds: ["aha-hf-2022", "dav-vn"],
  },
  {
    id: "enalapril-10",
    inn: "Enalapril maleate",
    innVi: "Enalapril",
    strength: "10 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Renitec 10 mg", "Enalapril 10 mg (Stada, DHG, generic)"],
    potassiumEffect: "increase",
    mechanismVi: "Ưc chế men chuyển (ACEI) — giảm aldosterone, giữ Kali.",
    adviceVi:
      "Đối chiếu hàm lượng 5/10/20 mg trên vỉ. Không tự thêm viên Kali. Tương tác NSAID và lợi tiểu giữ Kali.",
    relatedConditionIds: ["benh-than-man", "suy-tim", "tang-huyet-ap"],
    sourceIds: ["kdigo-ckd-2024", "aha-hf-2022", "dav-vn"],
  },
  {
    id: "perindopril-5",
    inn: "Perindopril arginine / tert-butylamine",
    innVi: "Perindopril",
    strength: "5 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Coversyl 5 mg", "Preterax (kết hợp indapamide)", "generic perindopril"],
    potassiumEffect: "increase",
    mechanismVi: "ACEI. Dạng kết hợp indapamide có thể kéo Kali hai hướng.",
    adviceVi:
      "Đọc thành phần: Coversyl đơn chất khác Preterax (có indapamide). Theo dõi Kali.",
    relatedConditionIds: ["tang-huyet-ap", "suy-tim"],
    sourceIds: ["esc-htn-2024", "dav-vn"],
  },
  {
    id: "losartan-50",
    inn: "Losartan potassium",
    innVi: "Losartan",
    strength: "50 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Cozaar 50 mg", "Hyperol", "Losartan Stada 50 mg"],
    potassiumEffect: "increase",
    mechanismVi: "Ưc chế thụ thể angiotensin II (ARB).",
    adviceVi:
      "Tên INN có chữ potassium (muối) — không phải viên bổ sung Kali. Vẫn có nguy cơ tăng Kali máu.",
    relatedConditionIds: ["benh-than-man", "tang-huyet-ap"],
    sourceIds: ["kdigo-ckd-2024", "dav-vn"],
  },
  {
    id: "valsartan-80",
    inn: "Valsartan",
    innVi: "Valsartan",
    strength: "80 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Diovan 80 mg", "Valsartan 80 mg (generic VN)"],
    potassiumEffect: "increase",
    mechanismVi: "ARB.",
    adviceVi: "Còn hàm lượng 160 mg. Có trong Entresto (kết hợp sacubitril).",
    relatedConditionIds: ["suy-tim", "tang-huyet-ap"],
    sourceIds: ["aha-hf-2022", "dav-vn"],
  },
  {
    id: "telmisartan-40",
    inn: "Telmisartan",
    innVi: "Telmisartan",
    strength: "40 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Micardis 40 mg", "Twynsta (telmisartan + amlodipine)", "generic"],
    potassiumEffect: "increase",
    mechanismVi: "ARB tác dụng dài.",
    adviceVi: "Kiểm tra viên kết hợp có phải chỉ amlodipine hay có lợi tiểu.",
    relatedConditionIds: ["tang-huyet-ap"],
    sourceIds: ["esc-htn-2024", "dav-vn"],
  },
  {
    id: "irbesartan-150",
    inn: "Irbesartan",
    innVi: "Irbesartan",
    strength: "150 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Aprovel 150 mg", "CoAprovel (irbesartan + HCTZ)", "generic"],
    potassiumEffect: "increase",
    mechanismVi: "ARB; hay dùng bệnh thận đái tháo đường.",
    adviceVi: "CoAprovel có HCTZ — Kali có thể không tăng như đơn chất.",
    relatedConditionIds: ["dai-thao-duong-than", "benh-than-man"],
    sourceIds: ["kdigo-ckd-2024", "dav-vn"],
  },
  {
    id: "entresto-100",
    inn: "Sacubitril / valsartan",
    innVi: "Sacubitril + valsartan",
    strength: "100 mg (49/51 mg) — còn 50 mg và 200 mg",
    formVi: "Viên nén bao phim",
    tradeNamesVn: ["Entresto 50 mg / 100 mg / 200 mg"],
    potassiumEffect: "increase",
    mechanismVi: "ARNI — valsartan ức chế RAAS, tăng nguy cơ tăng Kali.",
    adviceVi:
      "Không phối hợp ACEI (cách 36 giờ). Theo dõi Kali như MRA. Biệt dược Novartis được cấp phép tại VN.",
    relatedConditionIds: ["suy-tim", "tang-kali-mau"],
    sourceIds: ["aha-hf-2022", "dav-vn"],
  },
  {
    id: "furosemide-40",
    inn: "Furosemide",
    innVi: "Furosemid",
    strength: "40 mg",
    formVi: "Viên nén (còn ống tiêm 20 mg/2 ml)",
    tradeNamesVn: ["Lasix 40 mg", "Furosemide 40 mg (DHG và generic)"],
    potassiumEffect: "decrease",
    mechanismVi: "Lợi tiểu quai — tăng thải Kali niệu.",
    adviceVi:
      "Có thể hạ Kali, hạ magie. Người suy tim vừa dùng spironolactone vừa furosemide: Kali hai chiều.",
    relatedConditionIds: ["suy-tim", "ha-kali-mau", "benh-than-man"],
    sourceIds: ["aha-hf-2022", "dav-vn"],
  },
  {
    id: "hctz-25",
    inn: "Hydrochlorothiazide",
    innVi: "Hydrochlorothiazid",
    strength: "25 mg",
    formVi: "Viên nén / viên kết hợp",
    tradeNamesVn: [
      "Hydrochlorothiazide 25 mg",
      "Nhiều viên hạ áp kết hợp (losartan/HCTZ, valsartan/HCTZ)",
    ],
    potassiumEffect: "decrease",
    mechanismVi: "Lợi tiểu thiazide — thải Kali.",
    adviceVi: "Đọc thành phần viên 'một viên hai chất'. Có thể cần bù Kali theo toa.",
    relatedConditionIds: ["tang-huyet-ap", "ha-kali-mau"],
    sourceIds: ["esc-htn-2024", "dav-vn"],
  },
  {
    id: "indapamide-15",
    inn: "Indapamide",
    innVi: "Indapamid",
    strength: "1,5 mg giải phóng kéo dài",
    formVi: "Viên bao",
    tradeNamesVn: ["Natrilix SR 1,5 mg", "Indapamide 1,5 mg generic"],
    potassiumEffect: "decrease",
    mechanismVi: "Giống thiazide — hạ Kali, hạ natri.",
    adviceVi: "Phổ biến trong phác đồ huyết áp VN. Theo dõi điện giải người già.",
    relatedConditionIds: ["tang-huyet-ap", "ha-kali-mau"],
    sourceIds: ["esc-htn-2024", "bytvn-thn", "dav-vn"],
  },
  {
    id: "kcl-600",
    inn: "Potassium chloride",
    innVi: "Kali clorid",
    strength: "600 mg (≈ 8 mEq Kali)",
    formVi: "Viên giải phóng chậm",
    tradeNamesVn: ["Slow-K 600 mg", "Kaleorid", "Kali clorid 600 mg"],
    potassiumEffect: "increase",
    mechanismVi: "Bổ sung Kali trực tiếp.",
    adviceVi:
      "Chỉ dùng khi có chỉ định hạ Kali. Nguy hiểm nếu CKD, đang ACEI+MRA, hoặc tăng Kali. Không nhai viên chậm.",
    relatedConditionIds: ["ha-kali-mau", "tang-kali-mau"],
    sourceIds: ["dav-vn"],
  },
  {
    id: "panangin",
    inn: "Potassium aspartate + magnesium aspartate",
    innVi: "Kali aspartat + magie aspartat",
    strength: "Thường 158 mg K-aspartat + 140 mg Mg-aspartat / viên (xem hộp)",
    formVi: "Viên bao / ống uống",
    tradeNamesVn: ["Panangin", "Asparcam (một số thị trường)", "generic K-Mg aspartat"],
    potassiumEffect: "increase",
    mechanismVi: "Thực phẩm thuốc bổ sung Kali và magie.",
    adviceVi: "Người bệnh vẫn phải đối chiếu hàm lượng trên nhãn. Không dùng khi tăng Kali.",
    relatedConditionIds: ["ha-kali-mau"],
    sourceIds: ["dav-vn"],
  },
  {
    id: "kalimate",
    inn: "Calcium polystyrene sulfonate",
    innVi: "Calci polystyrene sulfonat",
    strength: "5 g / gói (bột) — theo nhãn",
    formVi: "Bột uống",
    tradeNamesVn: ["Kalimate", "generic nhựa gắn Kali calci"],
    potassiumEffect: "decrease",
    mechanismVi: "Nhựa trao đổi ion gắn Kali ở ruột.",
    adviceVi:
      "Dùng khi tăng Kali theo chỉ định. Tách giờ với thuốc khác. Không thay thế lọc máu cấp cứu.",
    relatedConditionIds: ["tang-kali-mau", "loc-mau", "benh-than-man"],
    sourceIds: ["kdigo-ckm-2025", "dav-vn"],
  },
  {
    id: "cotrimoxazole",
    inn: "Sulfamethoxazole + trimethoprim",
    innVi: "Sulfamethoxazol + trimethoprim",
    strength: "400 mg / 80 mg (còn 800/160 mg)",
    formVi: "Viên nén",
    tradeNamesVn: ["Bactrim", "Biseptol", "Cotrimoxazole 480 mg"],
    potassiumEffect: "increase",
    mechanismVi:
      "Trimethoprim chẹn kênh ENaC kiểu amiloride — giữ Kali, đặc biệt người già/CKD.",
    adviceVi: "Cảnh giác khi đang ACEI/ARB/spironolactone.",
    relatedConditionIds: ["tang-kali-mau", "benh-than-man"],
    sourceIds: ["kdigo-ckd-2024", "dav-vn"],
  },
  {
    id: "diclofenac-50",
    inn: "Diclofenac sodium / potassium",
    innVi: "Diclofenac",
    strength: "50 mg",
    formVi: "Viên bao tan trong ruột",
    tradeNamesVn: ["Voltaren 50 mg", "Diclofenac 50 mg (Stada, DHG)"],
    potassiumEffect: "increase",
    mechanismVi: "NSAID giảm prostaglandin thận — giảm thải Kali, giảm GFR.",
    adviceVi: "Tránh tự mua khi đang ACEI + lợi tiểu ('triple whammy').",
    relatedConditionIds: ["benh-than-man", "tang-kali-mau"],
    sourceIds: ["kdigo-ckd-2024", "dav-vn"],
  },
  {
    id: "ibuprofen-400",
    inn: "Ibuprofen",
    innVi: "Ibuprofen",
    strength: "400 mg",
    formVi: "Viên nén / viên nang",
    tradeNamesVn: ["Brufen 400 mg", "Ibuprofen 400 mg generic"],
    potassiumEffect: "increase",
    mechanismVi: "NSAID.",
    adviceVi: "Thuốc không kê đơn vẫn ảnh hưởng Kali và thận.",
    relatedConditionIds: ["benh-than-man"],
    sourceIds: ["kdigo-ckd-2024", "dav-vn"],
  },
  {
    id: "digoxin-025",
    inn: "Digoxin",
    innVi: "Digoxin",
    strength: "0,25 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Digoxin 0,25 mg (Nhiệt đới, generic)"],
    potassiumEffect: "caution_both",
    mechanismVi:
      "Không phải thuốc giữ Kali, nhưng hạ Kali làm tăng độc tính digoxin (loạn nhịp).",
    adviceVi: "Giữ Kali trong khoảng bình thường. Thận trọng khi lợi tiểu mạnh.",
    relatedConditionIds: ["suy-tim", "ha-kali-mau"],
    sourceIds: ["aha-hf-2022", "dav-vn"],
  },
  {
    id: "insulin-human",
    inn: "Human insulin / insulin analog",
    innVi: "Insulin",
    strength: "100 IU/ml (lọ hoặc bút — xem nhãn)",
    formVi: "Dung dịch tiêm",
    tradeNamesVn: ["Insulatard", "Actrapid", "Mixtard", "Lantus", "NovoRapid", "Humalog"],
    potassiumEffect: "shift_into_cells",
    mechanismVi: "Đưa Kali vào tế bào — hạ Kali huyết thanh tạm thời.",
    adviceVi:
      "Dùng trong cấp cứu tăng Kali. Hạ đường huyết/nhịn ăn có thể hạ Kali. Không thay đổi chế độ Kali mạn chỉ vì insulin.",
    relatedConditionIds: ["dai-thao-duong-than", "tang-kali-mau", "ha-kali-mau"],
    sourceIds: ["kdigo-ckm-2025", "dav-vn"],
  },
  {
    id: "salbutamol",
    inn: "Salbutamol (albuterol)",
    innVi: "Salbutamol",
    strength: "100 microgam / nhát xịt",
    formVi: "Hít định liều; còn ống khí dung",
    tradeNamesVn: ["Ventolin Inhaler", "Ventolin Nebules", "generic salbutamol"],
    potassiumEffect: "shift_into_cells",
    mechanismVi: "Beta-2 agonist — đưa Kali vào tế bào.",
    adviceVi: "Liều khí dung cao dùng hỗ trợ tăng Kali cấp. Xịt hen thông thường ít đổi Kali.",
    relatedConditionIds: ["tang-kali-mau", "ha-kali-mau"],
    sourceIds: ["kdigo-ckm-2025", "dav-vn"],
  },
  {
    id: "prednisolone-5",
    inn: "Prednisolone / prednisone",
    innVi: "Prednisolon",
    strength: "5 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Prednisolone 5 mg", "Solupred (prednisolone)", "Medrol (methylprednisolon)"],
    potassiumEffect: "decrease",
    mechanismVi: "Corticoid khoáng có thể tăng thải Kali (tùy loại và liều).",
    adviceVi: "Liều cao kéo dài: theo dõi Kali, đường huyết, huyết áp.",
    relatedConditionIds: ["ha-kali-mau"],
    sourceIds: ["dav-vn"],
  },
  {
    id: "ciclosporin",
    inn: "Ciclosporin (cyclosporine)",
    innVi: "Ciclosporin",
    strength: "25 mg / 50 mg / 100 mg nang mềm — theo nhãn",
    formVi: "Nang mềm",
    tradeNamesVn: ["Sandimmun Neoral", "generic ciclosporin"],
    potassiumEffect: "increase",
    mechanismVi: "Ưc chế calcineurin — giảm thải Kali, có thể gây tăng Kali.",
    adviceVi: "Ghép tạng: theo dõi Kali chặt. Không tự uống NSAID.",
    relatedConditionIds: ["tang-kali-mau", "benh-than-man"],
    sourceIds: ["kdigo-ckd-2024", "dav-vn"],
  },
  {
    id: "tacrolimus",
    inn: "Tacrolimus",
    innVi: "Tacrolimus",
    strength: "0,5 mg / 1 mg / 5 mg",
    formVi: "Nang",
    tradeNamesVn: ["Prograf", "Advagraf", "generic tacrolimus"],
    potassiumEffect: "increase",
    mechanismVi: "Ưc chế calcineurin.",
    adviceVi: "Tương tự ciclosporin về Kali và thận.",
    relatedConditionIds: ["tang-kali-mau"],
    sourceIds: ["kdigo-ckd-2024", "dav-vn"],
  },
  {
    id: "enoxaparin",
    inn: "Enoxaparin sodium",
    innVi: "Enoxaparin",
    strength: "40 mg / 0,4 ml; 60 mg / 0,6 ml (bơm tiêm đóng sẵn)",
    formVi: "Tiêm dưới da",
    tradeNamesVn: ["Lovenox", "Clexane", "Enoxaparin generic"],
    potassiumEffect: "increase",
    mechanismVi: "Heparin/LMWH có thể ức chế aldosterone — tăng Kali khi dùng kéo dài.",
    adviceVi: "Theo dõi Kali người CKD, đái tháo đường, đang ACEI.",
    relatedConditionIds: ["tang-kali-mau"],
    sourceIds: ["dav-vn"],
  },
  {
    id: "captopril-25",
    inn: "Captopril",
    innVi: "Captopril",
    strength: "25 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Captopril 25 mg (Nhiều nhà máy VN)", "Capoten (tham chiếu)"],
    potassiumEffect: "increase",
    mechanismVi: "ACEI tác dụng ngắn; hay dùng cấp cứu huyết áp tại VN.",
    adviceVi: "Vẫn giữ Kali như các ACEI khác nếu dùng lặp lại.",
    relatedConditionIds: ["tang-huyet-ap", "tang-kali-mau"],
    sourceIds: ["bytvn-thn", "dav-vn"],
  },
  {
    id: "amlodipine-note",
    inn: "Amlodipine besylate",
    innVi: "Amlodipin",
    strength: "5 mg",
    formVi: "Viên nén",
    tradeNamesVn: ["Norvasc 5 mg", "Amlodipine 5 mg (Stada, DHG)", "Twynsta (kết hợp)"],
    potassiumEffect: "caution_both",
    mechanismVi:
      "Chẹn calci dihydropyridine — ảnh hưởng Kali không đáng kể so với ACEI/lợi tiểu.",
    adviceVi:
      "Đưa vào danh mục vì rất phổ biến tại VN; Kali đổi chủ yếu do thuốc kèm trong viên kết hợp.",
    relatedConditionIds: ["tang-huyet-ap"],
    sourceIds: ["esc-htn-2024", "dav-vn"],
  },
];

export function getMedicine(id: string): Medicine | undefined {
  return MEDICINES.find((item) => item.id === id);
}
